import random

quotes = [
    {"quote": "The wound is the place where the Light enters you.", "author": "Rumi"},
    {"quote": "Fear is the cheapest room in the house. I would like to see you living in better conditions.", "author": "Hafez"},
    {"quote": "Human beings are members of a whole, in creation of one essence and soul.", "author": "Saadi"},
    {"quote": "Knowledge is power and dignity.", "author": "Ferdowsi"},
    {"quote": "Be happy for this moment. This moment is your life.", "author": "Omar Khayyam"},
    {"quote": "Experience is the teacher of wisdom.", "author": "Avicenna"},
    {"quote": "The wound is where the light enters you.", "author": "Rumi"},
    {"quote": "Waste no more time arguing what a good man should be. Be one.", "author": "Marcus Aurelius"},
    {"quote": "The soul becomes dyed with the color of its thoughts.", "author": "Marcus Aurelius"},
    {"quote": "He who has a why to live can bear almost any how.", "author": "Nietzsche"},
    {"quote": "No tree can grow to heaven unless its roots reach down to hell.", "author": "Carl Jung"},
    {"quote": "Between stimulus and response there is a space.", "author": "Viktor Frankl"},
    {"quote": "To live without hope is to cease to live.", "author": "Dostoevsky"},
    {"quote": "Perceive that which cannot be seen with the eye.", "author": "Miyamoto Musashi"},
    {"quote": "Knowing others is intelligence; knowing yourself is wisdom.", "author": "Lao Tzu"},
    {"quote": "The wound is the place where the Light enters you.", "author": "Rumi"},
    {"quote": "Why do you stay in prison when the door is so wide open?", "author": "Rumi"},
    {"quote": "What you seek is seeking you.", "author": "Rumi"},
    {"quote": "As you start to walk on the way, the way appears.", "author": "Rumi"},
    {"quote": "Raise your words, not your voice. It is rain that grows flowers, not thunder.", "author": "Rumi"},
    {"quote": "Set your life on fire. Seek those who fan your flames.", "author": "Rumi"},
    {"quote": "Wear gratitude like a cloak and it will feed every corner of your life.", "author": "Rumi"},
    {"quote": "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "author": "Rumi"},
    {"quote": "Don't grieve. Anything you lose comes round in another form.", "author": "Rumi"},
    {"quote": "When you let go of who you are, you become what you might be.", "author": "Rumi"},
    {"quote": "Fear is the cheapest room in the house. I would like to see you living in better conditions.", "author": "Hafez"},
    {"quote": "Stay close to anything that makes you glad you are alive.", "author": "Hafez"},
    {"quote": "I wish I could show you, when you are lonely or in darkness, the astonishing light of your own being.", "author": "Hafez"},
    {"quote": "Now is the time to know that all that you do is sacred.", "author": "Hafez"},
    {"quote": "The small man builds cages for everyone he knows, while the sage who has to duck his head when the moon is low keeps dropping keys all night long.", "author": "Hafez"},
    {"quote": "Plant seeds of happiness, hope, success, and love.", "author": "Hafez"},
    {"quote": "Even after all this time, the sun never says to the earth, 'You owe me.'", "author": "Hafez"},
    {"quote": "An awake heart is like a sky that pours light.", "author": "Hafez"},
    {"quote": "Human beings are members of a whole, in creation of one essence and soul.", "author": "Saadi"},
    {"quote": "Have patience. All things are difficult before they become easy.", "author": "Saadi"},
    {"quote": "A little fragrance always clings to the hand that gives roses.", "author": "Saadi"},
    {"quote": "Whoever acquires knowledge and does not practice it resembles him who plows and leaves unsown.", "author": "Saadi"},
    {"quote": "A wise enemy is better than a foolish friend.", "author": "Saadi"},
    {"quote": "Speak little and listen much.", "author": "Saadi"},
    {"quote": "Whoever has no patience has no wisdom.", "author": "Saadi"},
    {"quote": "Knowledge is power and dignity.", "author": "Ferdowsi"},
    {"quote": "Wisdom is the eye of the soul.", "author": "Ferdowsi"},
    {"quote": "Honor is greater than wealth.", "author": "Ferdowsi"},
    {"quote": "Good name remains after death.", "author": "Ferdowsi"},
    {"quote": "A wise man turns chance into good fortune.", "author": "Ferdowsi"},
    {"quote": "A kingdom survives through justice.", "author": "Ferdowsi"},
    {"quote": "Be happy for this moment. This moment is your life.", "author": "Omar Khayyam"},
    {"quote": "The moving finger writes; and, having writ, moves on.", "author": "Omar Khayyam"},
    {"quote": "Tomorrow? Why tomorrow? We only have today.", "author": "Omar Khayyam"},
    {"quote": "Take the present and enjoy it.", "author": "Omar Khayyam"},
    {"quote": "Life passes swiftly; seize the day.", "author": "Omar Khayyam"},
    {"quote": "Experience is the teacher of wisdom.", "author": "Avicenna"},
    {"quote": "The world is divided into men who have wit and no religion and men who have religion and no wit.", "author": "Avicenna"},
    {"quote": "Knowledge of anything, since all things have causes, is not acquired or complete unless it is known by its causes.", "author": "Avicenna"},
    {"quote": "The body and soul are not separate.", "author": "Avicenna"},
    {"quote": "The way is not in the sky. The way is in the heart.", "author": "Attar of Nishapur"},
    {"quote": "The cure for pain is in the pain.", "author": "Attar of Nishapur"},
    {"quote": "Lose yourself completely, return to the root of the root of your own soul.", "author": "Attar of Nishapur"},
    {"quote": "A thousand mysteries are hidden in a grain of dust.", "author": "Attar of Nishapur"},
    {"quote": "Waste no more time arguing what a good man should be. Be one.", "author": "Marcus Aurelius"},
    {"quote": "You have power over your mind—not outside events. Realize this, and you will find strength.", "author": "Marcus Aurelius"},
    {"quote": "The soul becomes dyed with the color of its thoughts.", "author": "Marcus Aurelius"},
    {"quote": "If it is not right, do not do it; if it is not true, do not say it.", "author": "Marcus Aurelius"},
    {"quote": "The happiness of your life depends upon the quality of your thoughts.", "author": "Marcus Aurelius"},
    {"quote": "The impediment to action advances action. What stands in the way becomes the way.", "author": "Marcus Aurelius"},
    {"quote": "Luck is what happens when preparation meets opportunity.", "author": "Seneca"},
    {"quote": "Difficulties strengthen the mind, as labor does the body.", "author": "Seneca"},
    {"quote": "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", "author": "Seneca"},
    {"quote": "He suffers more than necessary who suffers before it is necessary.", "author": "Seneca"},
    {"quote": "As long as you live, keep learning how to live.", "author": "Seneca"},
    {"quote": "First say to yourself what you would be; and then do what you have to do.", "author": "Epictetus"},
    {"quote": "No man is free who is not master of himself.", "author": "Epictetus"},
    {"quote": "It is impossible for a man to learn what he thinks he already knows.", "author": "Epictetus"},
    {"quote": "Circumstances do not make the man, they reveal him.", "author": "Epictetus"},
    {"quote": "He who has a why to live can bear almost any how.", "author": "Nietzsche"},
    {"quote": "Become who you are.", "author": "Nietzsche"},
    {"quote": "He who fights with monsters should be careful lest he thereby become a monster.", "author": "Nietzsche"},
    {"quote": "There are no beautiful surfaces without a terrible depth.", "author": "Nietzsche"},
    {"quote": "One must still have chaos in oneself to give birth to a dancing star.", "author": "Nietzsche"},
    {"quote": "No tree, it is said, can grow to heaven unless its roots reach down to hell.", "author": "Carl Jung"},
    {"quote": "Who looks outside, dreams; who looks inside, awakes.", "author": "Carl Jung"},
    {"quote": "Until you make the unconscious conscious, it will direct your life and you will call it fate.", "author": "Carl Jung"},
    {"quote": "The privilege of a lifetime is to become who you truly are.", "author": "Carl Jung"},
    {"quote": "Those who have a why to live can bear almost any how.", "author": "Viktor Frankl"},
    {"quote": "When we are no longer able to change a situation, we are challenged to change ourselves.", "author": "Viktor Frankl"},
    {"quote": "Between stimulus and response there is a space. In that space is our power to choose our response.", "author": "Viktor Frankl"},
    {"quote": "To live without hope is to cease to live.", "author": "Dostoevsky"},
    {"quote": "The mystery of human existence lies not in just staying alive, but in finding something to live for.", "author": "Dostoevsky"},
    {"quote": "Much unhappiness has come into the world because of bewilderment and things left unsaid.", "author": "Dostoevsky"},
    {"quote": "Perceive that which cannot be seen with the eye.", "author": "Miyamoto Musashi"},
    {"quote": "Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.", "author": "Miyamoto Musashi"},
    {"quote": "Do not regret what you have done.", "author": "Miyamoto Musashi"},
    {"quote": "Think lightly of yourself and deeply of the world.", "author": "Miyamoto Musashi"},
    {"quote": "The unexamined life is not worth living.", "author": "Socrates"},
    {"quote": "Know thyself.", "author": "Socrates"},
    {"quote": "Beware the barrenness of a busy life.", "author": "Socrates"},
    {"quote": "Wonder is the beginning of wisdom.", "author": "Socrates"},
    {"quote": "We are what we repeatedly do. Excellence, then, is not an act but a habit.", "author": "Aristotle"},
    {"quote": "Knowing yourself is the beginning of all wisdom.", "author": "Aristotle"},
    {"quote": "Patience is bitter, but its fruit is sweet.", "author": "Aristotle"},
    {"quote": "Pleasure in the job puts perfection in the work.", "author": "Aristotle"},
    {"quote": "Quality is not an act, it is a habit.", "author": "Aristotle"},
    {"quote": "No man ever steps in the same river twice.", "author": "Heraclitus"},
    {"quote": "Character is destiny.", "author": "Heraclitus"},
    {"quote": "There is nothing permanent except change.", "author": "Heraclitus"},
    {"quote": "It does not matter how slowly you go so long as you do not stop.", "author": "Confucius"},
    {"quote": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius"},
    {"quote": "He who conquers himself is the mightiest warrior.", "author": "Confucius"},
    {"quote": "Wherever you go, go with all your heart.", "author": "Confucius"},
    {"quote": "The man who moves a mountain begins by carrying away small stones.", "author": "Confucius"},
    {"quote": "The journey of a thousand miles begins with a single step.", "author": "Lao Tzu"},
    {"quote": "Knowing others is intelligence; knowing yourself is wisdom.", "author": "Lao Tzu"},
    {"quote": "When I let go of what I am, I become what I might be.", "author": "Lao Tzu"},
    {"quote": "Mastering others is strength. Mastering yourself is true power.", "author": "Lao Tzu"},
    {"quote": "Nature does not hurry, yet everything is accomplished.", "author": "Lao Tzu"},
    {"quote": "Talent hits a target no one else can hit; genius hits a target no one else can see.", "author": "Schopenhauer"},
    {"quote": "A man can do what he wills, but he cannot will what he wills.", "author": "Schopenhauer"},
    {"quote": "Compassion is the basis of morality.", "author": "Schopenhauer"},
    {"quote": "Every man takes the limits of his own field of vision for the limits of the world.", "author": "Schopenhauer"},
    {"quote": "Life can only be understood backwards; but it must be lived forwards.", "author": "Kierkegaard"},
    {"quote": "The most common form of despair is not being who you are.", "author": "Kierkegaard"},
    {"quote": "Anxiety is the dizziness of freedom.", "author": "Kierkegaard"},
    {"quote": "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.", "author": "Kierkegaard"},
    {"quote": "Everyone thinks of changing the world, but no one thinks of changing himself.", "author": "Leo Tolstoy"},
    {"quote": "The two most powerful warriors are patience and time.", "author": "Leo Tolstoy"},
    {"quote": "If you want to be happy, be.", "author": "Leo Tolstoy"},
    {"quote": "Wrong does not cease to be wrong because the majority share in it.", "author": "Leo Tolstoy"},
    {"quote": "There is no greatness where there is not simplicity, goodness and truth.", "author": "Leo Tolstoy"},
    {"quote": "The heart has its reasons which reason knows nothing of.", "author": "Blaise Pascal"},
    {"quote": "All of humanity's problems stem from man's inability to sit quietly in a room alone.", "author": "Blaise Pascal"},
    {"quote": "Small minds are concerned with the extraordinary, great minds with the ordinary.", "author": "Blaise Pascal"},
    {"quote": "Knowing is not enough; we must apply. Willing is not enough; we must do.", "author": "Goethe"},
    {"quote": "Whatever you can do or dream you can, begin it.", "author": "Goethe"},
    {"quote": "Magic is believing in yourself.", "author": "Goethe"},
    {"quote": "None are more hopelessly enslaved than those who falsely believe they are free.", "author": "Goethe"},
    {"quote": "Imagination is more important than knowledge.", "author": "Albert Einstein"},
    {"quote": "Life is like riding a bicycle. To keep your balance, you must keep moving.", "author": "Albert Einstein"},
    {"quote": "Try not to become a man of success, but rather a man of value.", "author": "Albert Einstein"},
    {"quote": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein"},
    {"quote": "The important thing is not to stop questioning.", "author": "Albert Einstein"},
    {"quote": "Learning never exhausts the mind.", "author": "Leonardo da Vinci"},
    {"quote": "Iron rusts from disuse; water loses its purity from stagnation.", "author": "Leonardo da Vinci"},
    {"quote": "Simplicity is the ultimate sophistication.", "author": "Leonardo da Vinci"},
    {"quote": "He who loves practice without theory is like the sailor who boards ship without a rudder.", "author": "Leonardo da Vinci"},
    {"quote": "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", "author": "Abraham Lincoln"},
    {"quote": "I am a slow walker, but I never walk back.", "author": "Abraham Lincoln"},
    {"quote": "Whatever you are, be a good one.", "author": "Abraham Lincoln"},
    {"quote": "The best way to predict your future is to create it.", "author": "Abraham Lincoln"},
    {"quote": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "author": "Winston Churchill"},
    {"quote": "If you're going through hell, keep going.", "author": "Winston Churchill"},
    {"quote": "To improve is to change; to be perfect is to change often.", "author": "Winston Churchill"},
    {"quote": "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", "author": "Winston Churchill"},
    {"quote": "Appear weak when you are strong, and strong when you are weak.", "author": "Sun Tzu"},
    {"quote": "Victorious warriors win first and then go to war.", "author": "Sun Tzu"},
    {"quote": "Know yourself and know your enemy, and you need not fear a hundred battles.", "author": "Sun Tzu"},
    {"quote": "In the midst of chaos, there is also opportunity.", "author": "Sun Tzu"},
    {"quote": "Integrity is doing the right thing, even when no one is watching.", "author": "C. S. Lewis"},
    {"quote": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C. S. Lewis"},
    {"quote": "You can't go back and change the beginning, but you can start where you are and change the ending.", "author": "C. S. Lewis"},
    {"quote": "Do not pray for an easy life; pray for the strength to endure a difficult one.", "author": "Bruce Lee"},
    {"quote": "Absorb what is useful, discard what is useless, add what is uniquely your own.", "author": "Bruce Lee"},
    {"quote": "Knowing is not enough, we must apply. Willing is not enough, we must do.", "author": "Bruce Lee"},
    {"quote": "Be water, my friend.", "author": "Bruce Lee"},
    {"quote": "Don't count the days; make the days count.", "author": "Muhammad Ali"},
    {"quote": "He who is not courageous enough to take risks will accomplish nothing in life.", "author": "Muhammad Ali"},
    {"quote": "Service to others is the rent you pay for your room here on earth.", "author": "Muhammad Ali"},
    {"quote": "I hated every minute of training, but I said, don't quit.", "author": "Muhammad Ali"},
    {"quote": "Think lightly of yourself and deeply of the world.", "author": "Miyamoto Musashi"},
    {"quote": "Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.", "author": "Miyamoto Musashi"},
    {"quote": "Perceive that which cannot be seen with the eye.", "author": "Miyamoto Musashi"},
    {"quote": "Do not regret what you have done.", "author": "Miyamoto Musashi"},
    {"quote": "Accept everything just the way it is.", "author": "Miyamoto Musashi"},
    {"quote": "The privilege of a lifetime is to become who you truly are.", "author": "Carl Jung"},
    {"quote": "Who looks outside, dreams; who looks inside, awakes.", "author": "Carl Jung"},
    {"quote": "Everything that irritates us about others can lead us to an understanding of ourselves.", "author": "Carl Jung"},
    {"quote": "I am not what happened to me, I am what I choose to become.", "author": "Carl Jung"},
    {"quote": "When we are no longer able to change a situation, we are challenged to change ourselves.", "author": "Viktor Frankl"},
    {"quote": "What is to give light must endure burning.", "author": "Viktor Frankl"},
    {"quote": "Between stimulus and response there is a space.", "author": "Viktor Frankl"},
    {"quote": "Those who have a 'why' to live can bear with almost any 'how'.", "author": "Viktor Frankl"},
    {"quote": "To live without hope is to cease to live.", "author": "Fyodor Dostoevsky"},
    {"quote": "The mystery of human existence lies not in just staying alive, but in finding something to live for.", "author": "Fyodor Dostoevsky"},
    {"quote": "Much unhappiness has come into the world because of bewilderment and things left unsaid.", "author": "Fyodor Dostoevsky"},
    {"quote": "Pain and suffering are always inevitable for a large intelligence and a deep heart.", "author": "Fyodor Dostoevsky"},
    {"quote": "As long as you live, keep learning how to live.", "author": "Seneca"},
    {"quote": "He suffers more than necessary who suffers before it is necessary.", "author": "Seneca"},
    {"quote": "Sometimes even to live is an act of courage.", "author": "Seneca"},
    {"quote": "True happiness is to enjoy the present without anxious dependence upon the future.", "author": "Seneca"},
    {"quote": "Nothing great was ever achieved without enthusiasm.", "author": "Ralph Waldo Emerson"},
    {"quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson"},
    {"quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
    {"quote": "Make the most of yourself, for that is all there is of you.", "author": "Ralph Waldo Emerson"},
    {"quote": "Go confidently in the direction of your dreams. Live the life you have imagined.", "author": "Henry David Thoreau"},
    {"quote": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau"},
    {"quote": "Not until we are lost do we begin to understand ourselves.", "author": "Henry David Thoreau"},
    {"quote": "The price of anything is the amount of life you exchange for it.", "author": "Henry David Thoreau"},
    {"quote": "Fear is the mind-killer.", "author": "Frank Herbert"},
    {"quote": "Without change something sleeps inside us, and seldom awakens.", "author": "Frank Herbert"},
    {"quote": "The mystery of life isn't a problem to solve, but a reality to experience.", "author": "Frank Herbert"},
    {"quote": "Not all those who wander are lost.", "author": "J. R. R. Tolkien"},
    {"quote": "Little by little, one travels far.", "author": "J. R. R. Tolkien"},
    {"quote": "Faithless is he that says farewell when the road darkens.", "author": "J. R. R. Tolkien"},
    {"quote": "All we have to decide is what to do with the time that is given us.", "author": "J. R. R. Tolkien"},
    {"quote": "The best revenge is not to be like your enemy.", "author": "Marcus Aurelius"},
    {"quote": "Very little is needed to make a happy life.", "author": "Marcus Aurelius"},
    {"quote": "Loss is nothing else but change, and change is Nature's delight.", "author": "Marcus Aurelius"},
    {"quote": "Energy and persistence conquer all things.", "author": "Benjamin Franklin"},
    {"quote": "Well done is better than well said.", "author": "Benjamin Franklin"},
    {"quote": "An investment in knowledge pays the best interest.", "author": "Benjamin Franklin"},
    {"quote": "I've failed over and over and over again in my life. And that is why I succeed.", "author": "Michael Jordan"},
    {"quote": "Limits, like fears, are often just an illusion.", "author": "Michael Jordan"},
    {"quote": "Talent wins games, but teamwork and intelligence win championships.", "author": "Michael Jordan"},
    {"quote": "Pressure is a privilege.", "author": "Billie Jean King"},
    {"quote": "Champions keep playing until they get it right.", "author": "Billie Jean King"},
    {"quote": "The more difficult the victory, the greater the happiness in winning.", "author": "Pelé"},
    {"quote": "Dreams are not what you see in sleep, dreams are things which do not let you sleep.", "author": "A. P. J. Abdul Kalam"},
    {"quote": "This too shall pass", "author": "Arsha"},]

def get_random_quote():
    return random.choice(quotes)
