# Generated by Django 6.0.3 on 2026-06-21 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="habit",
            unique_together={("user", "name", "frequency")},
        ),
    ]
