# Generated by Django 6.0.3 on 2026-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="order",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
