# Generated by Django 6.0.3 on 2026-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitlog",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
